language: node_js
node_js:
 - "6.9"

branches:
  only:
    - master

before-script:
  - npm install -g firebase-tools
  - npm install -g @angular/cl
  
script:
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
